### ISSUE TITLE
Why are the overrides on require.extensions read only?

### ISSUE THREAD

**Issue by maxkorp** [electronjs/compile-cache#2]
I am using https://github.com/thlorenz/proxyquire for testing, which temporarily overrides the require.extensions values. Using electron-compile (and thus) this module makes them read only however. When I testing switching it to writable:true, I didn't experience any problems. Is this something I can PR in?

**Comment by anaisbetts** [comment]
I copy-pasta'd that from Atom's version, I don't know why they decided to make it read-only, go for it

**Comment by maxkorp** [comment]
Would you rather I pr against 0.6.3 (used in compile/compilers) or against latest (which doesn't currently work properly with those modules)?

**Comment by anaisbetts** [comment]
@maxkorp PR against master

**Comment by anaisbetts** [comment]
> (which doesn't currently work properly with those modules)?

wat?

**Comment by maxkorp** [comment]
I tried using compile-cache master on electron-compilers master and electron-compile master (and the updated version of electron-compilers based on master in electron-compile as well), and tests fail. IIRC the `doesn't parse invalid coffee` and `strips relative pathnames from html because they're stupid` are the two that fail.

**Comment by anaisbetts** [comment]
Hm, interesting

**Comment by maxkorp** [comment]
I'll make a separate issue for that :+1: . PR for the main issue here: #3

**Comment by maxkorp** [comment]
Fixed in #3 :+1:
