### ISSUE TITLE
Latest version causes test failures when used in electron-compile(rs)

### ISSUE THREAD

**Issue by maxkorp** [electronjs/compile-cache#4]
So i forked all 3 projects, and updated this with the contents of #3.
I then pointed electron-compilers at the latest version, and then pointed electron-compile at the latest version of this, as well as the version of compilers i just mentioned.

2 Tests fail: 
- [ ] 'The inline HTML compiler' - 'should remove protocol-relative URLs because they are dumb'
- [ ] 'The coffeescript compiler' - 'should fail on invalid.coffee'

Let me know if you'd rather have this issue logged in either of those modules instead of/ along with here

**Comment by anaisbetts** [comment]
@maxkorp Nope, this is fine, I'm going to work on this today as well as a few other improvements to compile-cache and friends

**Comment by maxkorp** [comment]
Cool, I've got a few small PRs to make as well (cleaning lib up, etc). Thanks for throwing all this together. It's been a huge boon for me and my team.

**Comment by maxkorp** [comment]
Worth noting, if I manually go in and make the changes from #3 to the installed copies of 0.6.3 (in both compile and compilers), tests still work just fine, so it's not that change. Something else between 0.6.3 and master.

**Comment by anaisbetts** [comment]
Both of these failures are fixed (and were caused by `isMinified` incorrectly deciding that small files are minified)
